import "./globals.css";
import { Header } from "@/Components/Header";
import { Nav } from "@/Components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full sm:pt-[60px] flex flex-col items-center pt-[30px]">
        <h1 className=" w-full px-4 xl:px-24 uppercase font-semibold text-3xl">
          marie.does.design
        </h1>
        <div className=" px-4 my-[6px] w-full xl:px-24 mx-[10px] xl:mx-24">
          <hr className="" style={{ color: "black", height: "1px" }} />
        </div>

        <Nav />

        {children}
      </body>
    </html>
  );
}
